### ISSUE TITLE
报错：当前版本过低，请先升级到手机QQ最新版本。

### ISSUE THREAD

**Issue by Core2002** [Karlatemp/mirai-console-example-plugin#1]
`C:\Users\Administrator\.jdks\corretto-1.8.0_265\bin\java.exe -Dfile.encoding=utf-8 -Dsun.jnu.encoding=utf-8 "-javaagent:D:\IntelliJ IDEA\IntelliJ IDEA 2020.3\lib\idea_rt.jar=61220:D:\IntelliJ IDEA\IntelliJ IDEA 2020.3\bin" -classpath C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\charsets.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\access-bridge-64.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\cldrdata.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\dnsns.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\jaccess.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\jfxrt.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\localedata.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\nashorn.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\sunec.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\sunjce_provider.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\sunmscapi.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\sunpkcs11.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\ext\zipfs.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\jce.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\jfr.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\jfxswt.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\jsse.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\management-agent.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\resources.jar;C:\Users\Administrator\.jdks\corretto-1.8.0_265\jre\lib\rt.jar;D:\mirai-console-example-plugin\build\classes\kotlin\test;D:\mirai-console-example-plugin\build\tmp\kapt3\classes\test;D:\mirai-console-example-plugin\build\classes\kotlin\main;D:\mirai-console-example-plugin\build\tmp\kapt3\classes\main;D:\Repository\junit\junit\4.12\junit-4.12.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\net.mamoe\mirai-console\1.0-M4\7759b9ffdabc17cd257489009d9b03b6c68c5bfc\mirai-console-1.0-M4.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\net.mamoe\mirai-console-pure\1.0-M4\c195af6afe9454d3fd1a0ec4a39c5aaecd8b97f9\mirai-console-pure-1.0-M4.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.4.10\ea29e063d2bbe695be13e9d044dcfb0c7add398e\kotlin-stdlib-1.4.10.jar;D:\Repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\net.mamoe\mirai-core-jvm\1.2.3\c491100813666126ead232a77315016193631790\mirai-core-jvm-1.2.3.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\net.mamoe.yamlkt\yamlkt-jvm\0.5.2\e19aab2cd32f8ccfedee9525300d6312c8657e9a\yamlkt-jvm-0.5.2.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-jdk8\1.3.9\ea79a6a3819c433805149cdb90307d3da92c36c6\kotlinx-coroutines-jdk8-1.3.9.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.4.10\998caa30623f73223194a8b657abd2baec4880ea\kotlin-stdlib-jdk8-1.4.10.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\19.0.0\efbff6752f67a7c9de3e4251c086a88e23591dfd\annotations-19.0.0.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\com.vdurmont\semver4j\3.1.0\de1248f09dfe8df3b021c84e0642ee222cceb13\semver4j-3.1.0.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.4.10\6229be3465805c99db1142ad75e6c6ddeac0b04c\kotlin-stdlib-common-1.4.10.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.4.10\e2b3c6695eee6085e606d96d685396dce23a3a06\kotlin-reflect-1.4.10.jar;D:\Repository\io\ktor\ktor-client-core-jvm\1.4.0\ktor-client-core-jvm-1.4.0.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-serialization\1.4.10\a6897987d7ebb7ad14ecb583c40b434cbb016caa\kotlin-serialization-1.4.10.jar;D:\Repository\org\jetbrains\kotlinx\kotlinx-coroutines-io-jvm\0.1.16\kotlinx-coroutines-io-jvm-0.1.16.jar;D:\Repository\org\jetbrains\kotlinx\kotlinx-io-jvm\0.1.16\kotlinx-io-jvm-0.1.16.jar;D:\Repository\org\jetbrains\kotlinx\kotlinx-coroutines-io\0.1.16\kotlinx-coroutines-io-0.1.16.jar;D:\Repository\org\jetbrains\kotlinx\kotlinx-io\0.1.16\kotlinx-io-0.1.16.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.4.10\30e46450b0bb3dbf43898d2f461be4a942784780\kotlin-stdlib-jdk7-1.4.10.jar;D:\Repository\io\ktor\ktor-client-cio-jvm\1.4.0\ktor-client-cio-jvm-1.4.0.jar;D:\Repository\io\ktor\ktor-http-cio-jvm\1.4.0\ktor-http-cio-jvm-1.4.0.jar;D:\Repository\io\ktor\ktor-http-jvm\1.4.0\ktor-http-jvm-1.4.0.jar;D:\Repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;D:\Repository\io\ktor\ktor-network-jvm\1.4.0\ktor-network-jvm-1.4.0.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-gradle-plugin-api\1.4.10\c06dc95764119b3188034c644805de9b76148806\kotlin-gradle-plugin-api-1.4.10.jar;D:\Repository\org\jetbrains\kotlinx\kotlinx-serialization-core-jvm\1.0.0-RC\kotlinx-serialization-core-jvm-1.0.0-RC.jar;D:\Repository\org\jetbrains\kotlinx\kotlinx-coroutines-core-jvm\1.3.9\kotlinx-coroutines-core-jvm-1.3.9.jar;D:\Repository\org\jetbrains\kotlinx\atomicfu\0.14.1\atomicfu-0.14.1.jar;D:\Repository\org\jetbrains\kotlinx\atomicfu-common\0.14.1\atomicfu-common-0.14.1.jar;D:\Repository\io\ktor\ktor-network-tls-jvm\1.4.0\ktor-network-tls-jvm-1.4.0.jar;D:\Repository\io\ktor\ktor-utils-jvm\1.4.0\ktor-utils-jvm-1.4.0.jar;D:\Repository\io\ktor\ktor-io-jvm\1.4.0\ktor-io-jvm-1.4.0.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\net.mamoe\mirai-core-qqandroid-jvm\1.2.3\b01d8744d19b0cb9d810963c2b38d56deea1a809\mirai-core-qqandroid-jvm-1.2.3.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.jline\jline\3.15.0\6c8d38639ac26de5ccb5bed947ce2fd40b7e2269\jline-3.15.0.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\org.fusesource.jansi\jansi\1.18\d9205bbcd4b5f9cd1effe752d18f73bd942d783f\jansi-1.18.jar;D:\Repository\org\jetbrains\kotlinx\atomicfu-jvm\0.14.4\atomicfu-jvm-0.14.4.jar;C:\Users\Administrator\.gradle\caches\modules-2\files-2.1\net.mamoe\kotlin-jvm-blocking-bridge-jvm\1.0.5\703d2fd052486f3f3d29e1e3fb4138dd5869805\kotlin-jvm-blocking-bridge-jvm-1.0.5.jar;D:\Repository\org\bouncycastle\bcprov-jdk15on\1.64\bcprov-jdk15on-1.64.jar;D:\Repository\org\jetbrains\kotlinx\kotlinx-serialization-protobuf-jvm\1.0.0-RC\kotlinx-serialization-protobuf-jvm-1.0.0-RC.jar RunConsoleKt
2020-12-28 09:50:12 I/main: Starting mirai-console...
2020-12-28 09:50:12 I/main: Backend: version 1.0-M4, built on 2020-09-13 02:22:00.
2020-12-28 09:50:12 I/main: Frontend Pure: version 1.0-M4, provided by Mamoe Technologies
2020-12-28 09:50:12 V/main: Loading configurations...
2020-12-28 09:50:13 V/main: Loading JVM plugins...
2020-12-28 09:50:13 V/main: 0 external PluginLoader(s) found. 
2020-12-28 09:50:13 V/main: 0 plugin(s) loaded.
2020-12-28 09:50:13 V/main: Loading PermissionService...
2020-12-28 09:50:13 V/main: Reloaded PermissionService settings.
2020-12-28 09:50:13 V/main: Loading built-in commands...
2020-12-28 09:50:14 V/main: Prepared built-in commands: help, login, permission, stop
2020-12-28 09:50:14 V/main: Enabling plugins...
2020-12-28 09:50:14 I/main: 0 plugin(s) enabled.
2020-12-28 09:50:14 I/main: mirai-console started successfully.
2020-12-28 09:50:14 E/org.example.example-plugin: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at org.example.myplugin.MyPluginMain.onEnable(MyPluginMain.kt:45)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
	at net.mamoe.mirai.console.plugin.PluginManager$INSTANCE.enable(PluginManager.kt:145)
	at RunConsoleKt.main(RunConsole.kt:12)
	at RunConsoleKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at RunConsoleKt.main(RunConsole.kt)
Caused by: kotlinx.serialization.SerializationException: Serializer for class 'MyNestedData' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:127)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:116)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at net.mamoe.mirai.console.internal.data.SerializerHelperKt$serializerMirai$1.invoke(serializerHelper.kt:47)
	at net.mamoe.mirai.console.internal.data.SerializerHelperKt.serializerMirai(serializerHelper.kt:79)
	at net.mamoe.mirai.console.internal.data.ValueFromKTypeImplKt.valueFromKTypeImpl(valueFromKTypeImpl.kt:100)
	at net.mamoe.mirai.console.data.PluginDataKt.valueFromKType(PluginData.kt:348)
	at net.mamoe.mirai.console.data.PluginDataKt.valueImpl(PluginData.kt:331)
	at org.example.myplugin.MySetting.<clinit>(MyPluginMain.kt:169)
	... 14 more
> ?
◆ Command list
/help
◆ Log in a bot account.
/login <id> <password>
◆ Manage permissions
/permission cancel <target> <permission>
/permission cancelall <target> <permission>
/permission listpermissions
/permission permit <target> <permission>
/permission permittedpermissions <target>
◆ Stop the whole world.
/stop
> login xxxxxxx xxxxxx
2020-12-28 09:50:59 I/Bot 3052524560: Logging in...
Login failed: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
2020-12-28 09:51:08 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> `

**Comment by Karlatemp** [comment]
mamoe/mirai#745
